### ISSUE TITLE
Can't build on Centos 6 (i386) from rtg2-0.9-2.el6.src.rpm as non-root user

### ISSUE THREAD

**Issue by Prophidys** [Prophidys/RTG2#39]
_From [c.cral...@googlemail.com](https://code.google.com/u/112862198299373336948/) on April 08, 2013 14:35:45_

What steps will reproduce the problem? 1. $ rpm -i rtg2-0.9-2.el6.src.rpm
2. $ cd rpmbuild/SPECS/
3. $ rpmbuild -ba rtg2.spec What is the expected output? What do you see instead? Should create RPM but get following error instead:
test -z "/usr/include" || /bin/mkdir -p "/home/webadmin/rpmbuild/BUILDROOT/rtg2-0.9-2.el6.i386/usr/include"
 /usr/bin/install -c -m 644 rtg.h rtgplot.h rtgcommon.h rtgdbi.h '/home/webadmin/rpmbuild/BUILDROOT/rtg2-0.9-2.el6.i386/usr/include'
make[3]: Leaving directory `/home/webadmin/rpmbuild/BUILD/rtg2-0.9/src'
make[2]: Leaving directory `/home/webadmin/rpmbuild/BUILD/rtg2-0.9/src'
make[1]: Leaving directory `/home/webadmin/rpmbuild/BUILD/rtg2-0.9/src'
Making install in etc
make[1]: Entering directory `/home/webadmin/rpmbuild/BUILD/rtg2-0.9/etc'
/bin/sh /home/webadmin/rpmbuild/BUILD/rtg2-0.9/config/install-sh -d /usr/etc
/bin/sh /home/webadmin/rpmbuild/BUILD/rtg2-0.9/config/install-sh -d /usr/web
mkdir: cannot create directory `/usr/web': Permission denied
mkdir: cannot create directory `/usr/web': Permission denied
make[1]: *** [installdirs] Error 1
make[1]: Leaving directory `/home/webadmin/rpmbuild/BUILD/rtg2-0.9/etc'
make: *** [install-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.Gd0zvx (&#37;install)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Gd0zvx (&#37;install) What version of the product are you using? On what operating system? rtg2-0.9-2.el6.src.rpm Please provide any additional information below. Would like to be able to use RPMs for easy deployment. Any assistance would be appreciated. Thank you...

_Original issue: http://code.google.com/p/rtg2/issues/detail?id=42_

**Comment by bewing** [comment]
Should we close this issue out, as the spec file wasn't imported into github?

**Comment by Prophidys** [comment]
Yes, I will close this issue, we can handle this build problem to add build example on different platform we have test. Travis-ci allready do this job for ubuntu.
