### ISSUE TITLE
Bad syntax in etc/createdb.in

### ISSUE THREAD

**Issue by bewing** [Prophidys/RTG2#45]
mysql rtg < rtg.sql
ERROR 1064 (42000) at line 31: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'unsigned DOUBLE NOT NULL,
  KEY ifInOctets_idx (dtime)
)' at line 5

Should be rate DOUBLE unsigned NOT NULL.

**Comment by Prophidys** [comment]
I'm closing this issue fixed in #46
